### ISSUE TITLE
move to .net core!

### ISSUE THREAD

**Issue by xiaolu6t** [LitJSON/litjson#54]
who can move it to .net core?
It's very important for me.Anyone help?

**Comment by Skquark** [comment]
I needed an update to be compatible with the new .net core too.  Building to Windows Store in Unity using this component for UnityMaterialUI, and ran into some errors that are keeping me from porting over, thus we can't run our app on Hololens like it needs to. Here are the problems:
Assets\MaterialUI\Utils\LitJson\JsonReader.cs(405,24): error CS1061: 'TextReader' does not contain a definition for 'Close' and no extension method 'Close' accepting a first argument of type 'TextReader' could be found
~~I fixed this one by replacing reader.Close (); with reader.Dispose();

Assets\MaterialUI\Utils\LitJson\JsonMapper.cs(173,22)&(205,22): error CS1061: 'Type' does not contain a definition for 'GetInterface' and no extension method 'GetInterface' accepting a first argument of type 'Type' could be found

...\LitJson\JsonMapper.cs(317,31): error CS1061: 'Type' does not contain a definition for 'IsClass' and no extension method 'IsClass' accepting a first argument of type 'Type' could be found
...\LitJson\JsonMapper.cs(372,32): error CS1061: 'Type' does not contain a definition for 'IsEnum' and no extension method 'IsEnum' accepting a first argument of type 'Type' could be found

I tried using the legacy versions of the System classes by doing this:
#if NETFX_CORE
using Type = WinRTLegacy.Type;
#else
using Type = System.Type;
#endif
But sadly it wasn't one of the available ones, and I'm not exactly sure what's going on in this code to be able to replace it with alternative methods.  Anybody else smart enough to update this for Microsoft's moot changes that make our lives more difficult?  Probably not too hard, but this isn't my realm.  Thanks..

**Comment by devlead** [comment]
I've got a .NET Core compatible version could PR that if interest still exist? Probably will regardless.

**Comment by Skquark** [comment]
That would be amazing!  I was starting to give up hope since this project hasn't been updated for 2 years and I wasn't sure what I could do.  This has been the main thorn that has been keeping me from porting my game to Hololens, and it was designed for that.  I think other people could use a .NET Core update for this to be used on Universal Windows 10 Apps, so you should probably branch it, or incorporate it with the awaited v1.0 update.. Thanks, looking forward to getting it going.

**Comment by devlead** [comment]
@Skquark UWP would mean .NET Standard 1.4, currently targeting 1.6, but don't think I'm using anything that's not in 1.4. I'll try to adjust in my fork and test in a UWP app and then PR here.
And can then provide binaries if anyone wants to test it.

**Comment by cstensonpv** [comment]
@devlead How did it go with making it work for UWP?
Would possibly be able to help out because I need it to work on UWP.

**Comment by devlead** [comment]
@cstensonpv I started work in this PR https://github.com/WCOMAB/litjson/pull/3

That fork has a few other improvements too, haven't had time/prioritize to finish it though.

Tried compiling as a UWP with no dependencies and only two rows would need to change for that, so I would suggest an ifdef for those.

Don't know the state of Litjson, if @lbv needs/want assistance with maintaining it, One option is to continue the work in the fork and get a PoC going.

**Comment by devlead** [comment]
Have it working on .NET Core in till PR https://github.com/WCOMAB/litjson/pull/3

Tried compiling it on UWP and only 2 lines needed to change for it to compile under UWP, so a simple ifdef would sort that if one created a multitarget nuget i.e.

Don't know the status of Litjson, been pretty quite from @lbv when asking if assistance needed/wanted for it. One option would be to continue the work in the fork.

**Comment by cstensonpv** [comment]
@cstensonpv :) Will need to look at it. I'm not really familiar with compiling for UWP. Usually a unity/web developer. Guess it might be easier if you have a compiled version to share than explaining the procedure

**Comment by devlead** [comment]
I can supply a binary you can test with if you like.

**Comment by cstensonpv** [comment]
Okay! I tred once more to build a solutions but did only manage to build if for .net 4+. I would appreaciate a binary. Feel free to contact me on my email. (thinks it is visible at github?) @devlead

**Comment by devlead** [comment]
Binaries are now available on nuget
https://www.nuget.org/packages/LitJson

Blog post about the release available at
https://litjson.net/blog/2018/01/litjson-v0.10.0-released

**Comment by cstensonpv** [comment]
Great! However as a unity developer all binares are targeting .NET 4.X which isn't supported by the editor (max 3.5 is supported). Is it possible to compile it for a lower version ?

**Comment by devlead** [comment]
@cstensonpv yes it should be, currently not by the .NET core CLI, but with the correct targeting pack or or a separate build it should be. I've raised issue #69 to track this.
